### ISSUE TITLE
Troubleshooting missing metrics

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [newrelic/newrelic-airflow-plugin#14]
Hello,

I tried to create a NewRelic chart showing the following Airflow metrics:

```
ti_failures | Overall task instances failures
ti_successes | Overall task instances successes
```

However, it appears these metrics are not in NewRelic.

I tried this NRQL query:

```
FROM Metric select ti_successes
```

and it didn't have any counters.  (This is after running a DAG where some tasks succeeded.)

How would I go about troubleshooting this, please?

**Comment by umaannamalai** [comment]
Hi @atsalolikhin-spokeo ! To troubleshoot this issue, here’s a few options you may consider:

1. Install an editable version of the newrelic-airflow-plugin (using `pip install -e`) into your environment. From there, you can add log statements into the plugin to determine whether the `ti_successes` and `ti_failures` metrics are being generated and sent with the harvester.

2. Airflow can be set up [to send metrics](https://airflow.apache.org/docs/stable/metrics.html) to StatsD. New Relic does have StatsD monitoring integration which you can find more information about [here](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2). You could consider trying this approach to view Airflow metrics sent to StatsD directly in New Relic.

Hope this helps!

**Comment by atsalolikhin-spokeo** [comment]
Hi @umaannamalai !  Thanks for your kind reply.  What is the "harvester" ?  I am not familiar with this term. Is this a part of the plugin?  Which file in the newrelic-airflow-plugin should I modify to add log statements?  I kind of like the idea of adding an option to turn on debug logging in the plugin.  (I like it better than complicating our architecture by adding another component, statsd, though I do appreciate you giving me a couple of options, that's very helpful, thank you.)  :)

**Comment by umaannamalai** [comment]
Hi @atsalolikhin-spokeo ! Debugging within the plugin is a great option. 

To do this, I would recommend exploring `newrelic-airflow-plugin/src/newrelic_airflow_plugin/newrelic_plugin.py`. If you take a look at the `Harvester` class in this file, you'll see there is a `send_for_metric` [function](https://github.com/newrelic/newrelic-airflow-plugin/blob/master/src/newrelic_airflow_plugin/newrelic_plugin.py#L31) which may be a good starting point for adding debug statements.

**Comment by atsalolikhin-spokeo** [comment]
Well, don't laugh, but in the process of deploying my changes to add debug logging, I realized that I only installed the plugin on the Web server instance, not on the worker instance. It needs to be installed on both servers, of course.

Once I added the newrelic-airflow-plugin on the worker, the missing metrics appeared!

Thanks again for your kind assistance!
